name: surveyscout
description: "Cari data tak pernah semudah ini!"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  iconify_flutter: ^0.0.5
  google_fonts: ^6.2.1
  properties: ^2.1.1
  flutter_iconify: ^1.2.6
  fluentui_system_icons: ^1.1.273
  fluentui_icons: ^1.0.0
  get_storage: ^2.1.1
  webview_flutter: ^4.10.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0

flutter:
  fonts:
    - family: SourceSans3
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
          weight: 400

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_7pt_SemiCondensed-Medium.ttf
          weight: 400  # Sesuaikan dengan bobot sebenarnya
        - asset: assets/fonts/NunitoSans_7pt-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans_7pt-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans_7pt-LightItalic.ttf
          weight: 400
          style: italic

  uses-material-design: true

  assets:
    - assets/images/surveyscoutlogo.png
    - assets/images/surveyscout1.png
    - assets/images/google.png
    - assets/images/merekrut.png
    - assets/images/selesai.png
    - assets/images/butuhtinjau.png
    - assets/images/dikerjakan.png
    - assets/images/duaharilalu.png
    - assets/images/pdfexcel.png
    - assets/images/chat.png
    - assets/images/aksi.png
    - assets/images/2bulanlagi.png
    - assets/images/foto1.png
    - assets/images/foto2.png
    - assets/images/foto3.png
    - assets/images/taskantor.png
    - assets/images/taskantorjam.png
    - assets/images/titik3.png
    - assets/images/chat.png
    - assets/images/peringatan.png
    - assets/images/gradienmerah.png
    - assets/images/butuhtinjau2.png
    - assets/images/selesai2.png
    - assets/images/download.png
    - assets/images/chat3.png
    - assets/images/saya.png
    - assets/images/proyek.png
    - assets/images/ataujadilah.png
    - assets/images/kepuasananda.png
    - assets/images/caridata.png
    - assets/images/klien.png
    - assets/images/surveyor.png
    - assets/images/responden.png
    - assets/images/namalengkap.png
    - assets/images/jeniskelamin.png
    - assets/images/tanggallahir.png
    - assets/images/nomortelepon.png
    - assets/images/nik.png
    - assets/images/namabank.png
    - assets/images/namaperusahaan.png
    - assets/images/jenisperusahaan.png
    - assets/images/pinakses.png
    - assets/images/hurufi.png
    - assets/images/proyek2.png
    - assets/images/chat4.png
    - assets/images/dikerjakan2.png
    - assets/images/rekrutmen.png
    - assets/images/dikerjakan3.png
    - assets/images/rekrutmen2.png
    - assets/images/hermanwalton.png
    - assets/images/hermanwalton2.png
    - assets/images/centang.png
    - assets/images/bagaskaraputra.png
    - assets/images/richardsantoso.png
    - assets/images/richardsantoso2.png
    - assets/images/layananpelanggan.png
    - assets/images/layananpelanggan2.png
    - assets/images/notifikasipembayaran.png
    - assets/images/saya2.png
    - assets/images/ptwidyamandala.png
    - assets/images/surabaya.png
    - assets/images/pinakses2.png
    - assets/images/panahkanan.png
    - assets/images/autentikasi.png
    - assets/images/perangkat.png
    - assets/images/rekening.png
    - assets/images/riwayat.png
    - assets/images/informasiumum.png
    - assets/images/newsletter.png
    - assets/images/caridari100.png
    - assets/images/titik32.png
    - assets/images/2bulanlagi2.png
    - assets/images/limaratus.png
    - assets/images/semarang.png
    - assets/images/tersedia.png
    - assets/images/proyeksaya.png
    - assets/images/online.png
    - assets/images/uang.png
    - assets/images/taskantor2.png
    - assets/images/centang2.png
    - assets/images/download2.png
    - assets/images/proyeksaya2.png
    - assets/images/tersedia2.png
    - assets/images/qrislogo.png
